language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install --upgrade pip
script:
- python --version
deploy:
  provider: pypi
  user: Sasha_Chernykh
  password:
    secure: R2ZygTWCFqsxPBDWZ0YDkTysnFuKNQsc4m6GoQ2KGNOt8/iccMK9Z1hr7BN/qyUhS14L0udzwiC9B0V7hEDZm+ZaR9QSouETcsMhdIZkBDbdXbUUh+02R6VtnjEXYUc9fYdbSfcC9iA0ha5MPodQbnXipv450plgI7SQFttQMbbf6+F//Sz3t/eu2ij5Vfy1wPjuj5Z3cTLJvudQcA9LeoYHY0JkWUpin+wavC0Z0sbXorCIjbI4LDR04ef8CLH3IhMzrBZ9jJzl/ioMcC2FNbA6Fh6GX41BbZdTtOQl8BGkfnEuENgC6x0w0PD9gU59beLfGECDo34G5wniphxXJ+khHbkJW/OAycZYdj8nuaDRnq0EffK8OIzLHUiODsglg1kKSl5DUKjw4jN1WpI6nPEkiunivBzS2NLnZa+SLFHLWM04tUGe0Z1J1glfmtOFoi/0J+Pq0yiMNaliMpw2MgATzxSzOTniNoMajxmKb23jaM0awIuN/sAw4CXeP3aiMhI11XGtzGRWYER1jEV7tRDlgf0P82soQUeJ1h7FWXKyg8/qdZSqn7iAEZdhjxr7hf1ZJcBa0dELH3CMSr4mnEf46/7F7TDxCsXLpCp98XnhXhTSMIBFuKj1+kYzO/g+ANy3MQTCScLzbE2B3NJZ8vVSqzH7a68G2bOKu1MoWQk=
  on:
    branch: SashaPypiDeploy
